---

git_repo: git@github.com:GetMeez/meez.git

server_user_password: "{{ vault_server_user_password }}"

db_user: "{{ vault_db_user }}"
db_name: "{{ vault_db_name }}"
db_password: "{{ vault_db_password }}"
db_host: "{{ vault_db_host }}"

# Set this flag to true so you can checkout code from a private git repository
# which is setup with an SSH key.
ssh_forward_agent: true

project_name: meez
application_name: meez

# Note that this PPA doesn't guarantee timely updates in case of security issues.
# Simply remove these two vars below if you prefer to use the official PPA and
# default Python version that came with your Linux distro.
#
# More info here: https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
enable_deadsnakes_ppa: yes
virtualenv_python_version: python3.7
